/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "EmissionsApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MySupabaseAnonRoleKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
