name: Weekly CO2 Emissions Check Cron Job

on:
  schedule:
    # Run weekly at 00:00 on Wednesday
    - cron: '0 0 * * 3'
  workflow_dispatch:  # Allows manual triggering of the workflow.

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write
  id-token: write

jobs:
  co2-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install CO2 library
        run: npm install @tgwf/co2
      
      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Create data directory
        run: mkdir -p ./data

      - name: Run CO2 Emissions Check
        run: node scripts/co2-emissions-check.js websites-to-check-weekly-list.json
      
      - name: Generate sites_to_check.json file
        run: node scripts/generate-sites-to-check.js websites-to-check-weekly-list.json

      - name: Commit and push if there are changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git pull origin
          git status
          if [ -n "$(git status --porcelain)" ]; then
            git add src/content/emissions_results.csv
            git add public/data/emissions_results.json
            git add public/data/error_log.json
            git add public/data/sites_to_check.json
            git commit -m "Update WEEKLY emissions & sites to check data"
            git push
          else
            echo "No changes to commit"
          fi
