# name: Weekly CO2 Emissions Check Cron Job

# on:
#   schedule:
#     - cron: '0 0 * * 3'  # Weekly at midnight on Wednesday
#   workflow_dispatch:

# permissions:
#   contents: write
#   id-token: write

# jobs:
#   co2-check:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20.x'

#       - name: Install dependencies
#         run: |
#           npm install @tgwf/co2
#           npm install puppeteer
#           npm install @supabase/supabase-js
#           npm install p-limit

#       - name: Create data directory
#         run: mkdir -p ./data

#       - name: Run CO2 Emissions Check
#         run: node scripts/co2-emissions-check.js websites-to-check-weekly-list.json
#         continue-on-error: true
#         env:
#           NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
#           SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

#       - name: Generate sites list
#         run: node scripts/generate-sites-list.js
#         env:
#           NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
#           SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

#       - name: Commit and push CSV file
#         run: |
#           git config --global user.email "action@github.com"
#           git config --global user.name "GitHub Action"
#           git pull origin
#           git add src/content/emissions_results.csv
#           git commit -m "Update weekly emissions CSV data" || echo "No changes to commit"
#           git push || echo "No changes to push"
